### ISSUE TITLE
PRs related to Type1.5 boot

### ISSUE THREAD

**Issue by hky1999** [arceos-hypervisor/axvisor#116]
* https://github.com/arceos-hypervisor/axvisor/pull/115
* https://github.com/arceos-hypervisor/arceos/pull/41
* https://github.com/arceos-hypervisor/axvm/pull/17
* https://github.com/arceos-hypervisor/x86_vcpu/pull/14
* https://github.com/arceos-hypervisor/axvcpu/pull/25
* https://github.com/arceos-hypervisor/axaddrspace/pull/11
* https://github.com/arceos-org/page_table_multiarch/pull/16
* https://github.com/arceos-org/axmm_crates/pull/7

```toml
[patch."https://github.com/arceos-hypervisor/arceos.git"]
axstd = { path = "./crates/arceos/ulib/axstd" }

[patch."https://github.com/arceos-hypervisor/x86_vcpu.git"]
x86_vcpu = { path = "./crates/x86_vcpu" }

[patch."https://github.com/arceos-hypervisor/axvm.git"]
axvm = { path = "./crates/axvm" }

[patch."https://github.com/arceos-hypervisor/axvcpu.git"]
axvcpu = { path = "./crates/axvcpu" }

[patch."https://github.com/arceos-hypervisor/axaddrspace.git"]
axaddrspace = { path = "./crates/axaddrspace" }

[patch.crates-io]
memory_addr = { path = "./crates/memory_addr/memory_addr" }
memory_set = { path = "./crates/memory_addr/memory_set" }
page_table_entry = { path = "./crates/page_table_multiarch/page_table_entry" }
page_table_multiarch = { path = "./crates/page_table_multiarch/page_table_multiarch" }
```
